# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-18 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlt', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=20)),
                ('teachers', models.ManyToManyField(to='rlt.Teacher')),
            ],
        ),
    ]
